const clamp=(value,min=0,max=1)=>Math.min(Math.max(value,min),max)
const lerp=(a,b,t)=>a+(b-a)*t
const smoothstep=(a,b,value)=>{const t=clamp((value-a)/(b-a));return t*t*(3-2*t)}
class SeededRandom{constructor(seed=8361){this.seed=seed>>>0}next(){this.seed=(1664525*this.seed+1013904223)>>>0;return this.seed/4294967296}}
class TwinWorld{
constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.dpr=Math.min(window.devicePixelRatio||1,1.75);this.progress=0;this.targetProgress=0;this.pointer={x:0,y:0,tx:0,ty:0};this.time=0;this.random=new SeededRandom();this.particles=this.createParticles(1150);this.terrain=this.createTerrain();this.resize();window.addEventListener('resize',()=>this.resize());window.addEventListener('pointermove',event=>{this.pointer.tx=(event.clientX/window.innerWidth-.5)*2;this.pointer.ty=(event.clientY/window.innerHeight-.5)*2},{passive:true});requestAnimationFrame(time=>this.frame(time))}
resize(){this.width=window.innerWidth;this.height=window.innerHeight;this.dpr=Math.min(window.devicePixelRatio||1,1.75);this.canvas.width=Math.round(this.width*this.dpr);this.canvas.height=Math.round(this.height*this.dpr);this.canvas.style.width=`${this.width}px`;this.canvas.style.height=`${this.height}px`;this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.focal=Math.min(this.width,this.height)*.92}
setProgress(progress){this.targetProgress=clamp(progress)}
createParticles(count){return Array.from({length:count},()=>({x:(this.random.next()-.5)*38,y:(this.random.next()-.36)*18,z:7-this.random.next()*180,size:.25+this.random.next()*1.15,pulse:this.random.next()*Math.PI*2,warm:this.random.next()>.88}))}
heightAt(x,z){const ridge=Math.exp(-Math.pow(x/(4.1+Math.abs(z)*.035),2));const peakA=Math.exp(-Math.pow((z+40)/16,2))*8.4;const peakB=Math.exp(-Math.pow((z+91)/22,2))*14.5;const peakC=Math.exp(-Math.pow((z+135)/13,2))*8.2;const erosion=Math.sin(x*1.35+z*.22)*.78+Math.sin(x*.43-z*.39)*.48;return ridge*(peakA+peakB+peakC+erosion)-5.4+Math.sin((x+z)*1.7)*.12}
createTerrain(){const rows=70,columns=34,result=[];for(let row=0;row<rows;row++){const z=-12-row*2.25,line=[];for(let column=0;column<columns;column++){const x=lerp(-18,18,column/(columns-1));line.push({x,y:this.heightAt(x,z),z})}result.push(line)}return result}
camera(){const p=this.progress;let x,y,z,yaw,pitch;if(p<.2){const t=p/.2;x=lerp(0,-.6,t);y=lerp(.2,1.1,t);z=lerp(12,5,t);yaw=lerp(0,-.03,t);pitch=lerp(0,-.015,t)}else if(p<.52){const t=(p-.2)/.32;x=lerp(-.6,-3.2,t);y=lerp(1.1,3.2,t);z=lerp(5,-61,t);yaw=lerp(-.03,.08,t);pitch=lerp(-.015,-.06,t)}else if(p<.84){const t=(p-.52)/.32;x=lerp(-3.2,3.8,t);y=lerp(3.2,8.2,t);z=lerp(-61,-124,t);yaw=lerp(.08,-.09,t);pitch=lerp(-.06,-.11,t)}else{const t=(p-.84)/.16;x=lerp(3.8,0,t);y=lerp(8.2,13.2,t);z=lerp(-124,-148,t);yaw=lerp(-.09,0,t);pitch=lerp(-.11,-.16,t)}x+=this.pointer.x*.32;y-=this.pointer.y*.18;return{x,y,z,yaw,pitch}}
project(point,camera){let x=point.x-camera.x,y=point.y-camera.y,z=point.z-camera.z;const cosy=Math.cos(camera.yaw),siny=Math.sin(camera.yaw);const rx=x*cosy-z*siny,rz=x*siny+z*cosy;x=rx;z=rz;const cosp=Math.cos(camera.pitch),sinp=Math.sin(camera.pitch);const ry=y*cosp-z*sinp,rz2=y*sinp+z*cosp;y=ry;z=rz2;const depth=-z;if(depth<.6)return null;const scale=this.focal/depth;return{x:this.width*.5+x*scale,y:this.height*.5-y*scale,depth,scale}}
background(){const p=this.progress,warm=smoothstep(.14,.2,p)*(1-smoothstep(.31,.39,p)),summit=smoothstep(.8,1,p),ctx=this.ctx;const gradient=ctx.createRadialGradient(this.width*.5,this.height*.42,0,this.width*.5,this.height*.5,Math.max(this.width,this.height)*.8);const r=Math.round(lerp(5,23,warm)+summit*3),g=Math.round(lerp(8,10,warm)+summit*9),b=Math.round(lerp(10,7,warm)+summit*14);gradient.addColorStop(0,`rgb(${r+5},${g+10},${b+13})`);gradient.addColorStop(1,`rgb(${r},${g},${b})`);ctx.fillStyle=gradient;ctx.fillRect(0,0,this.width,this.height)}
drawParticles(camera){const ctx=this.ctx,mountain=smoothstep(.2,.45,this.progress);for(const particle of this.particles){const drift=Math.sin(this.time*.00025+particle.pulse)*.13;const point=this.project({x:particle.x+drift,y:particle.y,z:particle.z},camera);if(!point||point.x<-20||point.x>this.width+20||point.y<-20||point.y>this.height+20)continue;const alpha=clamp((1-point.depth/145)*(.18+mountain*.55),.02,.58)*(.65+Math.sin(this.time*.0015+particle.pulse)*.35);const size=clamp(particle.size*point.scale*.02,.35,2.1);ctx.fillStyle=particle.warm?`rgba(215,126,87,${alpha})`:`rgba(200,224,232,${alpha})`;ctx.fillRect(point.x,point.y,size,size)}}
drawTerrain(camera){const reveal=smoothstep(.2,.42,this.progress);if(reveal<=.01)return;const ctx=this.ctx;ctx.lineJoin='round';for(let row=this.terrain.length-2;row>=0;row--){const current=this.terrain[row],next=this.terrain[row+1];for(let col=0;col<current.length-1;col++){const points=[current[col],current[col+1],next[col+1],next[col]].map(point=>this.project(point,camera));if(points.some(point=>!point))continue;const averageDepth=points.reduce((sum,point)=>sum+point.depth,0)/4,fog=clamp(1-averageDepth/115),lift=clamp((current[col].y+6)/17),alpha=reveal*fog*.56;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fillStyle=`rgba(${Math.round(10+lift*24)},${Math.round(23+lift*32)},${Math.round(31+lift*42)},${alpha})`;ctx.fill();if((row+col)%2===0){ctx.strokeStyle=`rgba(143,180,194,${alpha*.19})`;ctx.lineWidth=.45;ctx.stroke()}}}ctx.save();ctx.globalCompositeOperation='screen';for(let row=0;row<this.terrain.length;row+=3){const line=this.terrain[row];ctx.beginPath();let started=false;for(const point3d of line){const point=this.project(point3d,camera);if(!point)continue;if(!started){ctx.moveTo(point.x,point.y);started=true}else ctx.lineTo(point.x,point.y)}ctx.strokeStyle=`rgba(127,163,176,${reveal*.055})`;ctx.lineWidth=.65;ctx.stroke()}ctx.restore()}
drawCore(){const exit=smoothstep(.08,.29,this.progress),alpha=1-exit;if(alpha<.01)return;const ctx=this.ctx,cx=this.width*.5+this.pointer.x*14,cy=this.height*.47+this.pointer.y*8-exit*this.height*.25,base=Math.min(this.width,this.height)*lerp(.135,.075,exit),pulse=1+Math.sin(this.time*.0013)*.035;ctx.save();ctx.translate(cx,cy);ctx.globalCompositeOperation='screen';const glow=ctx.createRadialGradient(0,0,0,0,0,base*2.2);glow.addColorStop(0,`rgba(226,211,194,${.25*alpha})`);glow.addColorStop(.35,`rgba(139,104,88,${.12*alpha})`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,base*2.2,0,Math.PI*2);ctx.fill();for(let ring=0;ring<7;ring++){const radius=base*pulse*(.7+ring*.08),points=96;ctx.beginPath();for(let i=0;i<=points;i++){const angle=i/points*Math.PI*2,deform=1+Math.sin(angle*(3+ring%3)+this.time*.001+ring)*.07+Math.cos(angle*7-this.time*.0007)*.025,perspective=.74+ring*.022,x=Math.cos(angle)*radius*deform,y=Math.sin(angle)*radius*deform*perspective;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(${210-ring*8},${201-ring*10},${190-ring*11},${alpha*(.35-ring*.025)})`;ctx.lineWidth=ring===0?1.3:.7;ctx.stroke()}for(let ring=0;ring<3;ring++){ctx.save();ctx.rotate(this.time*.00012*(ring%2?-1:1)+ring);ctx.scale(1,.28+ring*.12);ctx.beginPath();ctx.arc(0,0,base*(1.18+ring*.18),0,Math.PI*2);ctx.strokeStyle=`rgba(207,177,159,${alpha*(.34-ring*.07)})`;ctx.lineWidth=.7;ctx.stroke();ctx.restore()}ctx.restore()}
drawHorizon(camera){const reveal=smoothstep(.82,.97,this.progress);if(!reveal)return;const ctx=this.ctx,center=this.project({x:0,y:10,z:-172},camera);if(!center)return;const glow=ctx.createRadialGradient(center.x,center.y,0,center.x,center.y,this.width*.38);glow.addColorStop(0,`rgba(185,219,230,${.22*reveal})`);glow.addColorStop(.3,`rgba(89,141,158,${.08*reveal})`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,this.width,this.height);ctx.save();ctx.translate(center.x,center.y);ctx.rotate(this.time*.00008);for(let i=0;i<6;i++){const angle=Math.PI*2*i/6;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(angle)*this.width*.34,Math.sin(angle)*this.width*.34);ctx.strokeStyle=`rgba(190,222,231,${.1*reveal})`;ctx.lineWidth=.7;ctx.stroke()}ctx.restore()}
frame(time){this.time=time;this.progress+=(this.targetProgress-this.progress)*.055;this.pointer.x+=(this.pointer.tx-this.pointer.x)*.04;this.pointer.y+=(this.pointer.ty-this.pointer.y)*.04;const camera=this.camera();this.background();this.drawParticles(camera);this.drawTerrain(camera);this.drawHorizon(camera);this.drawCore();requestAnimationFrame(next=>this.frame(next))}}
const canvas=document.querySelector('#world'),world=new TwinWorld(canvas),loader=document.querySelector('#loader'),loaderBar=document.querySelector('#loader-bar'),loaderCount=document.querySelector('#loader-count'),loaderPhase=document.querySelector('#loader-phase'),phases=['RECOVERING MEMORY','MAPPING VOICE','LINKING CONTINUITY','INITIALIZING SECOND SELF'],start=performance.now(),loaderDuration=2300
function loaderFrame(now){const raw=clamp((now-start)/loaderDuration),eased=1-Math.pow(1-raw,3),count=Math.round(eased*100);loaderBar.style.width=`${count}%`;loaderCount.textContent=String(count).padStart(3,'0');loaderPhase.textContent=phases[Math.min(Math.floor(count/25),phases.length-1)];if(raw<1)requestAnimationFrame(loaderFrame);else setTimeout(()=>{loader.classList.add('loader--done');document.body.classList.add('is-ready');setTimeout(()=>loader.remove(),900)},220)}requestAnimationFrame(loaderFrame)
const progressLine=document.querySelector('#progress-line'),progressCount=document.querySelector('#progress-count'),chapterItems=[...document.querySelectorAll('#progress-chapters li')],architecture=document.querySelector('#architecture'),architectureTrack=document.querySelector('#architecture-track'),architectureCount=document.querySelector('#architecture-count'),architectureBar=document.querySelector('#architecture-bar'),sceneWash=document.querySelector('#scene-wash');let raf=0
function updateScroll(){const scrollable=Math.max(document.documentElement.scrollHeight-innerHeight,1),progress=clamp(scrollY/scrollable);world.setProgress(progress);progressLine.style.height=`${progress*100}%`;progressCount.textContent=String(Math.round(progress*100)).padStart(2,'0');chapterItems.forEach((item,index)=>item.classList.toggle('is-active',progress>=index/(chapterItems.length-1)-.04));const warm=smoothstep(.12,.19,progress)*(1-smoothstep(.29,.37,progress));sceneWash.style.opacity=String(warm*.48);const rect=architecture.getBoundingClientRect(),travel=Math.max(architecture.offsetHeight-innerHeight,1),local=clamp(-rect.top/travel),mobile=innerWidth<=800,cardTravel=mobile?88:66;architectureTrack.style.transform=`translate3d(${local*-cardTravel*4}vw,0,0)`;architectureCount.textContent=`${String(Math.round(local*100)).padStart(2,'0')}%`;architectureBar.style.width=`${local*100}%`;raf=0}
function onScroll(){if(!raf)raf=requestAnimationFrame(updateScroll)}addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);updateScroll()
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('in-view')})},{threshold:.15});document.querySelectorAll('section h2, section h3, .origin__large, .layers__item, .ascent__route li, .trajectory__paths span').forEach(element=>observer.observe(element))
